name: Mikroways Site Deployment (Hugo)

on:
  push:
    branches:
      - main
      - preview

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo manually
        run: |
          curl -sL https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_extended_0.122.0_Linux-64bit.tar.gz | tar xzf - -C /usr/local/bin hugo
          hugo version

      - name: Build
        run: hugo

      # Solo deploy a GitHub Pages si es main
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

      # Para preview, solo crear artifact
      - name: Upload Preview Artifact
        if: github.ref == 'refs/heads/preview'
        uses: actions/upload-artifact@v4
        with:
          name: preview-site
          path: ./public